export const AREA_NAME = [
  "北海道・東北",
  "関東",
  "北陸・甲信越",
  "中部",
  "関西",
  "中国",
  "四国",
  "九州・沖縄",
];

export const PREFECTURES_DATA = [
  [
    { params: "Hokkaido", name: "北海道" },
    { params: "Aomori", name: "青森" },
    { params: "Iwate", name: "岩手" },
    { params: "Miyagi", name: "宮城" },
    { params: "Akita", name: "秋田" },
    { params: "Yamagata", name: "山形" },
    { params: "Fukushima", name: "福島" },
  ],
  [
    { params: "Ibaraki", name: "茨城" },
    { params: "Tochigi", name: "栃木" },
    { params: "Gunma", name: "群馬" },
    { params: "Saitama", name: "埼玉" },
    { params: "Chiba", name: "千葉" },
    { params: "Tokyo", name: "東京" },
    { params: "Kanagawa", name: "神奈川" },
  ],
  [
    { params: "Niigata", name: "新潟" },
    { params: "Toyama", name: "富山" },
    { params: "Ishikawa", name: "石川" },
    { params: "Fukui", name: "福井" },
    { params: "Yamanashi", name: "山梨" },
    { params: "Nagano", name: "長野" },
  ],
  [
    { params: "Gifu", name: "岐阜" },
    { params: "Shizuoka", name: "静岡" },
    { params: "Aichi", name: "愛知" },
    { params: "Mie", name: "三重" },
  ],
  [
    { params: "Shiga", name: "滋賀" },
    { params: "Kyoto", name: "京都" },
    { params: "Osaka", name: "大阪" },
    { params: "Hyogo", name: "兵庫" },
    { params: "Nara", name: "奈良" },
    { params: "Wakayama", name: "和歌山" },
  ],
  [
    { params: "Tottori", name: "鳥取" },
    { params: "Shimane", name: "島根" },
    { params: "Okayama", name: "岡山" },
    { params: "Hiroshima", name: "広島" },
    { params: "Yamaguchi", name: "山口" },
  ],
  [
    { params: "Tokushima", name: "徳島" },
    { params: "Kagawa", name: "香川" },
    { params: "Ehime", name: "愛媛" },
    { params: "Kochi", name: "高知" },
  ],
  [
    { params: "Fukuoka", name: "福岡" },
    { params: "Saga", name: "佐賀" },
    { params: "Nagasaki", name: "長崎" },
    { params: "Kumamoto", name: "熊本" },
    { params: "Oita", name: "大分" },
    { params: "Miyazaki", name: "宮崎" },
    { params: "Kagoshima", name: "鹿児島" },
    { params: "Okinawa", name: "沖縄" },
  ],
];

// 各都道府県のコードは大エリアマスタAPIから取得
//エンドポイント http://webservice.recruit.co.jp/hotpepper/large_area/v1/?format=json&key=*****
export const AREA_CODE: { [key: string]: string } = {
  Hokkaido: "Z041",
  Aomori: "Z051",
  Iwate: "Z052",
  Miyagi: "Z053",
  Akita: "Z054",
  Yamagata: "Z055",
  Fukushima: "Z056",
  Ibaraki: "Z015",
  Tochigi: "Z016",
  Gunma: "Z017",
  Saitama: "Z013",
  Chiba: "Z014",
  Tokyo: "Z011",
  Kanagawa: "Z012",
  Niigata: "Z061",
  Toyama: "Z062",
  Ishikawa: "Z063",
  Fukui: "Z064",
  Yamanashi: "Z065",
  Nagano: "Z066",
  Gifu: "Z031",
  Shizuoka: "Z032",
  Aichi: "Z033",
  Mie: "Z034",
  Shiga: "Z021",
  Kyoto: "Z022",
  Osaka: "Z023",
  Hyogo: "Z024",
  Nara: "Z025",
  Wakayama: "Z026",
  Tottori: "Z071",
  Shimane: "Z072",
  Okayama: "Z073",
  Hiroshima: "Z074",
  Yamaguchi: "Z075",
  Tokushima: "Z081",
  Kagawa: "Z082",
  Ehime: "Z083",
  Kochi: "Z084",
  Fukuoka: "Z091",
  Saga: "Z092",
  Nagasaki: "Z093",
  Kumamoto: "Z094",
  Oita: "Z095",
  Miyazaki: "Z096",
  Kagoshima: "Z097",
  Okinawa: "Z098",
};
